% this function implements coordinate descent for
% e-net regularized VAR(1) with active set iterations

function [beta, iter, epsilon] = lasso_var_single( ...
    X_mx, ... % design matrix
    Y_mx, ... % response variable
    lambda, ... % regularization parameter
    dist, ... % response distribution
    alpha, ... % elastic net mixing parameter
    beta_0, ... % starting value for initialization
    maxIter, ... % maximum iterations (cycles through coordinates)
    convCrit, ... % convergence criterion (L1 distance)
    intercept_idx) % index of intercept locations (for vectorized VAR)

% for the first cycle through the coordinates,
% do not do active set iteration
active_flag = 0;
[beta_k, epsilon] = update_var_coords(...
    beta_0, ...
    X_mx, ...
    Y_mx, ...
    lambda, ...
    alpha, ...
    dist, ...
    intercept_idx, ...
    active_flag);
iter = 1;

% for subsequent cycles, do active set iteration
% until convergence or until reaching maximum
% number of cycles
active_flag = 1;
while (epsilon > convCrit) && (iter < maxIter)
    [beta_k, epsilon] = update_var_coords(...
        beta_k, ...
        X_mx, ...
        Y_mx, ...
        lambda, ...
        alpha, ...
        dist, ...
        intercept_idx, ...
        active_flag);
    iter = iter + 1;
end
beta = beta_k;