function [out] = try_settings(data, lambda_path, ...
    dist, ...
    alpha, ...
    maxIter, ...
    convCrit)

% data dimensions
[~, p] = size(data);

% arrange data
[x, y] = regression_format(data, 1, 1);

% compute lasso estimates
beta0 = zeros(size(x, 2)*size(y, 2), 1);
[supports, convCheck] = lasso_supports( ...
        x, ...
        y, ...
        lambda_path, ...
        1:(p + 1):(p*(p + 1)),...
        dist, ...
        alpha, ...
        beta0, ...
        maxIter, ...
        convCrit);

out = [log10(lambda_path)' cellfun(@(x) size(x, 1), supports) convCheck];
